version: 0.2
phases:
  pre_build:
    on-failure: ABORT
    commands:
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws
      - REPOSITORY_URI=`aws ecr-public describe-repositories --region us-east-1 --repository-names ${ECR_REPOSITORY_NAME} | jq -r '.repositories[0].repositoryUri'`
      - if [ -z "${CODEBUILD_WEBHOOK_TRIGGER}" ] || [ "${CODEBUILD_WEBHOOK_TRIGGER}" = "branch/main" ]; then IMAGE_TAG=latest; else IMAGE_TAG=${CODEBUILD_WEBHOOK_TRIGGER#tag/}; fi
      - docker buildx create --use --name multiarch-builder
      - docker buildx inspect --bootstrap
  build:
    on-failure: ABORT
    commands:
      - docker buildx build --platform linux/amd64,linux/arm64 -t ${REPOSITORY_URI}:${IMAGE_TAG} --push .
  post_build:
    on-failure: ABORT
    commands:
      - echo "Multi-architecture build completed and pushed to ECR"
